### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [Creeland/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Creeland** [comment]
Hey @BillyMassey! 
I improved the mobile layout by adding a mobile meta tag and some using a media query to improve the sizing of some of the text.
[Here](https://splurty-cree-provinsal.herokuapp.com/) is the app on heroku

**Comment by BillyMassey** [comment]
Good Job!

Keep up the awesome work coding! :)
